# Generated by Django 4.1.1 on 2022-10-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='years',
            name='year',
        ),
        migrations.AddField(
            model_name='years',
            name='year',
            field=models.DateTimeField()
        )
    ]
