# Generated by Django 4.1.1 on 2022-10-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_years_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='years',
            name='year',
            field=models.DateField(),
        ),
    ]
